### ISSUE TITLE
Welcome to a new benchmarking repository!

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/benchmarking#1]
@jwagemann @jmunroe I know you are both (as am I) looking into doing some benchmarking studies of the Pangeo software stack.  I think it would be _really_ great if we could share our work on this, so I created this repository and added you both as contributors.

I have no time limit on this, but I am planning on doing some benchmarking and scaling studies for the PASC 2019 conference this June 2019.  I plan on putting my code and tooling to perform those studies in this repository, and you are both welcome to use these results and code as you see fit.  I also welcome you to add and help develop with me.

I think the next steps are to compile a list of benchmark operations that we want to perform for both compute and storage.  I'll create an issue for each, since I think they should be treated separately (but I could be convinced that we could have some integrated benchmarks, too).

**Comment by kmpaul** [comment]
Oh, and feel free to add other people to this issue (or as contributors to this repo), as you see fit.

**Comment by jmunroe** [comment]
I've recently committed to present Pangeo-related benchmarking results at C3DIS in May 2019 so I am *highly motivated* to make progress on this.  Thanks for setting up the repo!

**Comment by jwagemann** [comment]
Hi,
great idea and I am very happy to contribute and help to develop the benchmarking tests. On my side, I sent off the proposal to the Earth on AWS CfP last week. If it will be successful, I could start in May with the set up of Pangeo on AWS and the benchmarking tests.
Happy to join the discussions in the meantime.

**Comment by rabernat** [comment]
I'm glad to see this effort get started.

We have had several false starts on benchmarking. My advice is: start small, ship often. Rather than designing a massive grand scheme and [bikshedding](https://whatis.techtarget.com/definition/Parkinsons-law-of-triviality-bikeshedding) indefinitely, write some concrete benchmarks for specific, easy things and start pushing code.

Otherwise it will be hard to get this off the ground.

**Comment by kmpaul** [comment]
@rabernat Yes!  I agree.  I believe that the three of us (@jmunroe, @jwagemann, and me) all have fairly short deadlines for progress on this.

I'm also CCing the NCL team (@khallock, @rbrownrigg, @clyne) and @andersy005, @jukent, and @matt-long.

**Comment by kmpaul** [comment]
I think everyone has been welcomed, so closing.
