### ISSUE TITLE
Compute Benchmarks

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/benchmarking#2]
We need to compile a list of _compute_ benchmarks for the Pangeo stack.  As a start, I would consider basic _average_ operations, just as:

- annual / seasonal / monthly means
- global / regional means

I think these could be weighted means, depending on the data.

What other benchmarks do we need?

**Comment by jwagemann** [comment]
We might want to add:
* calculation of climatologies
* Anomalies

**Comment by kmpaul** [comment]
Ok.  We now have basic compute operations in the [benchmarks/ops.py](https://github.com/pangeo-data/benchmarking/blob/master/benchmarks/ops.py) file.

The current design assumes that an operation will be performed on an entire dataset (defined in [benchmarks/datasets.py](https://github.com/pangeo-data/benchmarking/blob/master/benchmarks/datasets.py)).  If you want more operations, feel free to add them to the `ops.py` file.
