### ISSUE TITLE
Remove PBS specific configuration

### ISSUE THREAD

**Issue by andersy005** [pangeo-data/benchmarking#21]
@tinaok, 

How about moving this line to your `~/.config/dask/jobqueue.yaml` config file?

https://github.com/pangeo-data/benchmarking/blob/aa683fb229676357704357e3c050769410604a2b/benchmarks/utils.py#L93

I've made it possible to run the benchmarks on other systems other than the ones that use PBS as a job scheduler. I am currently running the benchmarks on https://www.tacc.utexas.edu/systems/wrangler, which uses SLURM and I found out that the line above is PBS specific and should probably be put into a user's configuration file instead of being part of the arguments passed to 

https://github.com/pangeo-data/benchmarking/blob/aa683fb229676357704357e3c050769410604a2b/benchmarks/utils.py#L85-L95

**Comment by tinaok** [comment]
@andersy005 
ok for moving job_extra, thanks for running benchmark jobs in other clusters!
