### ISSUE TITLE
reorganising result (renaming temporal mean-> spatial mean ) problem??

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/benchmarking#27]
I noticed the total number of simulation for hal was same, but component of occurrence of operations was modified. 
@andersy005 
as you can see from here
https://github.com/pangeo-data/benchmarking/commit/cae802f791c090db5154eb2d518bff46b0cc29ed#diff-03d8f39476fc86dc5b76d6ce113748ee
this part you have twice the temporal_mean  operation in the same configuration.
Can it be because that when you re-named the operation, something went wrong?

**Comment by andersy005** [comment]
> Can it be because that when you re-named the operation, something went wrong?

Indeed! I am sorry about that. I used my editor's `find` and `replace` feature, and it is likely that I did it twice. I will open a PR to fix this soon

**Comment by tinaok** [comment]
thanks!  I'll replot the figures once I get the PR!

**Comment by andersy005** [comment]
@tinaok, 

This issue should be fixed by #28. Let me know if the data looks okay.
