### ISSUE TITLE
Which dataset shall be used for benchmarking

### ISSUE THREAD

**Issue by halehawk** [pangeo-data/benchmarking#39]
Since benchmarking will include I/O performance, I'd like to know which dataset I shall use for this purpose.

**Comment by guillaumeeb** [comment]
Hi @halehawk do you want to work on adding I/O performance tests in this repository? That would be welcomed.

You'd want to use a real dataset? Couldn't you try working with the fake dataset that can be generated by https://github.com/pangeo-data/benchmarking/blob/master/benchmarks/datasets.py?

**Comment by kmpaul** [comment]
I think a fake dataset would be fine.  As long as compression was not enabled.  Compressing fake data tends to not yield the same compression ratios or performance characteristics that real data does.

**Comment by rabernat** [comment]
I encourage you to look at what I have been doing with cloud storage benchmarking:
http://gallery.pangeo.io/repos/rabernat/earthcube2020_cloud_storage/cloud_storage.html

I am using a real dataset, a high-resolution ocean model simulation.

**Comment by kmpaul** [comment]
But on HPC, using the same (large) dataset requires downloading it to the local parallel FS.  If we can prevent the need to download and store the dataset at multiple locations just for benchmarking purposes, that would be great.

...But with that said, if we could allow *both* options (i.e., the ability to run with fake data *or* the ability to run with a real dataset(s)), that would be even better.

**Comment by kmpaul** [comment]
@rabernat I'll also point out that another problem with using real datasets is that *different* datasets can see vastly different I/O performance, depending on the operations being performed.  The throughput that we saw from benchmarks of the PyReshaper, for example, saw greater than 10x differences depending on the CESM output stream (atm, ocn, lnd, etc.) and resolution.

I/O can get very complex quickly.

**Comment by halehawk** [comment]
@rabernat Can we open a cloud storage store, then dataset.to_netcdf to this store?
