### ISSUE TITLE
A simple test of netcdf4 (hdf5) vs. zarr

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/benchmarking#6]
Let's generate a dataset with same chunking and compression to both netcdf4 and zarr, and then test these access approaches:
* using HSDS, which can do metadata preloading and then parallel byte-range extraction of HDF5 data on S3
* using Zarr
* using the new xarray ability to read HDF5 directly from S3

Key to this testing would be to use the same number of CPUs on both HSDS (a service which uses parallel processing behind the scenes) and Dask.

**Comment by rsignell-usgs** [comment]
@jreadey figured out this dataset used the shuffle filter and that had not yet been implemented in HSDS.  So we rewrote the dataset to turn off the shuffle filter.    We took the netcdf4 file, used `h5dump -sH` to examine the chunking/filtering, and then used `h5repack` to specify the filtering, only specifying `GZIP` (which is the same as `ZLIB`) instead of both `GZIP` and `SHUFFLE`:
```
h5repack -f zeta:GZIP=5 adcirc_01.nc adcirc_01d.nc
``` 
We also wrote a non-shuffled version of the zarr dataset to make sure we are comparing the same filter/chunking/compression on both zarr and netcdf4(hdf5).

**Comment by kmpaul** [comment]
I should point out that some non-Python I/O testing is being done by Haiying Xu (@halehawk) with the [IOR](https://github.com/hpc/ior) benchmarking utility.  It is a C utility that has lots of options for benchmarking I/O and different formats.  Haiying made a fork of IOR in the NCAR organization [NCAR/ior](https://github.com/NCAR/ior) in which she added Z5 capabilities.  We are assembling some results and I will have her put the runscripts and results in this repo.

**Comment by rsignell-usgs** [comment]
We have since found that NetCDF4 can be as performant as Zarr for reading on the Cloud:  https://medium.com/pangeo/cloud-performant-netcdf4-hdf5-with-zarr-fsspec-and-intake-3d3a3e7cb935
